name: bio-hub-representation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=11.6
  - cudatoolkit-dev=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - imageio
  - pyyaml
  - matplotlib
  - numpy
  - scikit-learn
  - scikit-image
  - tensorboard
  - opencv
  - h5py
